on:
  workflow_call:
    inputs:
      username:
        type: string
        required: true

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: call action-2
        uses: sffortytwo/data-pipeline-library/action-2@main
